# Generated by Django 2.1.5 on 2019-01-19 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190119_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='article',
        ),
        migrations.AddField(
            model_name='author',
            name='article',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Article'),
        ),
        migrations.AlterField(
            model_name='author',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], max_length=8, verbose_name='性别'),
        ),
    ]
