# Generated by Django 2.1.5 on 2019-01-19 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190119_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='connect',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(null=True, verbose_name='评论'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Article', verbose_name='文章'),
        ),
    ]
